version: "3"
services:
  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
  django:
    build: .
    ports:
      - "8000:8000"
    working_dir: "/usr/src/app"
    volumes:
      - ./:/usr/src/app
    command: "python3 manage.py runserver 0.0.0.0:8000"
    restart: always
volumes:
  pg-data:
